parameters:
#    presentology_main.example.class: Presentology\MainBundle\Example

services:
#    presentology_main.example:
#        class: %presentology_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
